### ISSUE TITLE
Permission error with saving

### ISSUE THREAD

**Issue by ThatGhost54** [donkirkby/svg-turtle#25]
This might be a stupid issue but it's been few years since I've done any coding so I'm struggling a bit. 

import turtle as Turtle
from svg_turtle import SvgTurtle as SVGTurtle

drawing = SVGTurtle(200, 200)
drawing.circle(100)

drawing.save_as('test.svg')

I've written this just to draw a circle and then export it as an svg but everytime I run it I get a permission error
```
Traceback (most recent call last):
  File "C:\Users\******\Desktop\PythonLearning.py", line 10, in <module>
    drawing.save_as('test.svg')
  File "C:\Users\******\AppData\Local\Programs\Python\Python312\Lib\site-packages\svg_turtle\svg_turtle.py", line 175, in save_as
    return canvas.to_drawing().saveas(filename, pretty, indent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\******\AppData\Local\Programs\Python\Python312\Lib\site-packages\svgwrite\drawing.py", line 132, in saveas
    self.save(pretty=pretty, indent=indent)
  File "C:\Users\******\AppData\Local\Programs\Python\Python312\Lib\site-packages\svgwrite\drawing.py", line 120, in save
    fileobj = io.open(self.filename, mode='w', encoding='utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test.svg'
>>>
```
Im sure this is a dumb issue but if I could get some help it would be appreciated.

**Comment by donkirkby** [comment]
The error message is telling you that the program doesn't have permission to write the file in the current directory. (I'd guess that you launched a Python window like IDLE, and the current directory is something like `C:\Program Files\IDLE`.) I'd suggest you use one of these two ways to solve the problem:
1. Write the full path, instead of just a file name in the current directory. Change `'test.svg'` to `'C:/Users/YourName/Documents/test.svg'`. Obviously, replace `YourName` with your user name, and be careful with slashes/backslashes. I think Python understands slashes in Windows, but I'm not sure. Read about backslashes in strings, raw strings, and the `pathlib` module, if you haven't already.
2. Ask the user where to save the file. This will give you a full path, formatted correctly:

       import tkinter.filedialog
       file_path = tkinter.filedialog.asksaveasfilename()
       drawing.save_as(file_path)

As you learn, I recommend [Stack Overflow] as a good place to ask questions. Read their advice on [how to ask a good question] to improve your chances of getting an answer.

How did you find out about SaVaGe Turtle? What are you using it for?

[Stack Overflow]: https://stackoverflow.com/tour
[how to ask a good question]: https://stackoverflow.com/help/how-to-ask

**Comment by ThatGhost54** [comment]
I'm trying to model some gears in FreeCAD but all the workbenches use metric measurements and I can't seem to find a gear tool that can create gears using imperial units so I wanted to try and make one where I can use the imperial units to generate the gears. 

seems like drawing on python is pretty simple but then I need to convert those drawing to svg so I can import them to FreeCAD, at least that was the plan. 

Thank you for your help
