### ISSUE TITLE
`goto` doesn't work as expected

### ISSUE THREAD

**Issue by useronym** [donkirkby/svg-turtle#7]
Given

```python
t = SvgTurtle(400, 300)
display(t.position())
t.goto(200, 150)
display(t.position())
t.forward(1)
display(t.position())
svg = t.to_svg()
display(SVG(svg))
svg
```

the output of which is 
```
(0.00,0.00)

(200.00,150.00)

(201.00,150.00)
```

The resulting svg is 
```svg
'<svg baseProfile="full" height="300px" version="1.1" width="400px" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><clipPath id="border_clip"><rect height="300" width="400" x="0" y="0" /></clipPath></defs><polyline clip-path="url(#border_clip)" fill="none" points="200.5,150.5 400.5,0.5 401.5,0.5" stroke="black" stroke-linecap="round" stroke-width="1" /></svg>'
```

**Comment by donkirkby** [comment]
Thanks for the bug report. The coordinate system in the turtle doesn't directly match the coordinate system in the SVG file, because I thought it was important to keep the standard behaviour of the turtle where (0, 0) is in the centre of the screen.
However, I think you should be able to make the turtle coordinates match the SVG coordinates by using the [`setworldcoordinates()` method]. Unfortunately, I see there's a bug in that.
I'll fix that bug, and then add a comment here showing you how to make the coordinates match.
Other than this issue, have you found the library useful?

[`setworldcoordinates()` method]: https://docs.python.org/3/library/turtle.html#turtle.setworldcoordinates

**Comment by donkirkby** [comment]
OK, the fix is in v0.4.1, and you can use it like this:

    from svg_turtle import SvgTurtle
    
    t = SvgTurtle(300, 200)
    t.getscreen().setworldcoordinates(0.5,
                                      (t.getscreen().window_height() + 0.5),
                                      t.getscreen().window_width() + 0.5,
                                      0.5)
    t.goto(10, 20)
    t.goto(30, 40)
    print(t.to_svg())

That produces a polyline like this in the SVG:

    <polyline clip-path="url(#border_clip)" fill="none" points="0.0,0.0 10.0,20.0 30.0,40.0" stroke="black" stroke-linecap="round" stroke-width="1" />

However, one downside is that these world coordinates reverse `t.left(angle)` and `t.right(angle)`. If you want world coordinates that are easy to compare with the SVG coordinates but still preserve angles, I'd suggest negating the `y` values:

    t.getscreen().setworldcoordinates(0.5,
                                      -(t.getscreen().window_height() + 0.5),
                                      t.getscreen().window_width() + 0.5,
                                      -0.5)

**Comment by useronym** [comment]
Awesome, thank you for the quick fix!

**Comment by donkirkby** [comment]
Glad to hear it's useful. I don't plan to add extra features beyond the standard turtle, but you could create a subclass if you wanted to add more features in your own project.
